### PR TITLE
DEV: Rename `not_started` status to `pending`.

### PR DESCRIPTION
**Pull request by tgxworld**
Resolves the following warning:

`Enum element 'not_started' in Webinar uses the prefix 'not_'. This has caused a conflict with auto generated negative scopes. Avoid using enum elements starting with 'not' where the positive form is also an element.`

### CODE REVIEW

**Review by eviltrout — APPROVED** [review]
Technically a breaking change during deploy as the enum name changes but I suspect few will notice.

**Comment by tgxworld** [comment]
The enum name change doesn’t affect the column since the value remains unchanged. The existing process will still be able to access the status with the old name while the deployment process is going on.

**Comment by eviltrout** [comment]
The front end code uses a string for the value. If the front end code thinks the string should be "not_started" but the server responds with "pending" wouldn't that fail the if statement?

**Comment by tgxworld** [comment]
@eviltrout That is a good point and something that I don't normally think about. Interesting that this problem hasn't surfaced before because we could have easily removed an attribute on a serializer resulting in the client side code being incompatible.

**Comment by eviltrout** [comment]
I'm sure this problem has surfaced a lot, just generally clients tend to refresh when they see errors. Also in this case it wouldn't stop the javascript from running and raise any errors, it would just work in a less effective way. That's why ultimately I was happy to approve it because the amount of people affected is not always worth the effort.

**Review by CvX — APPROVED** [review]
Merged `main` and fixed a conflict. LGTM!

**Pull request merged**
